export const revenue = [
  { month: "Mar", value: 28400, users: 1740 },
  { month: "Apr", value: 31800, users: 2010 },
  { month: "May", value: 34700, users: 2260 },
  { month: "Jun", value: 36900, users: 2510 },
  { month: "Jul", value: 41200, users: 2890 },
  { month: "Aug", value: 46820, users: 3284 },
];

export const customers = [
  {
    id: "cus_01",
    name: "Marina Costa",
    initials: "MC",
    email: "marina@orbitlabs.io",
    company: "Orbit Labs",
    plan: "Business",
    status: "Active",
    mrr: 1290,
    joined: "12 Aug 2026",
    activity: "2 min ago",
  },
  {
    id: "cus_02",
    name: "Theo Martins",
    initials: "TM",
    email: "theo@northstar.dev",
    company: "Northstar",
    plan: "Pro",
    status: "Active",
    mrr: 490,
    joined: "08 Aug 2026",
    activity: "18 min ago",
  },
  {
    id: "cus_03",
    name: "Ana Luiza",
    initials: "AL",
    email: "ana@lumina.studio",
    company: "Lumina Studio",
    plan: "Starter",
    status: "Trial",
    mrr: 190,
    joined: "03 Aug 2026",
    activity: "1 hr ago",
  },
  {
    id: "cus_04",
    name: "Caio Nunes",
    initials: "CN",
    email: "caio@vero.finance",
    company: "Vero Finance",
    plan: "Business",
    status: "Active",
    mrr: 1290,
    joined: "28 Jul 2026",
    activity: "3 hrs ago",
  },
  {
    id: "cus_05",
    name: "Sofia Ribeiro",
    initials: "SR",
    email: "sofia@atlas.health",
    company: "Atlas Health",
    plan: "Pro",
    status: "Past due",
    mrr: 490,
    joined: "19 Jul 2026",
    activity: "Yesterday",
  },
  {
    id: "cus_06",
    name: "Ravi Monteiro",
    initials: "RM",
    email: "ravi@arco.design",
    company: "Arco Design",
    plan: "Free",
    status: "Active",
    mrr: 0,
    joined: "11 Jul 2026",
    activity: "2 days ago",
  },
];

export const transactions = [
  {
    id: "NX-84029",
    customer: "Orbit Labs",
    value: 1290,
    method: "Visa •••• 4242",
    status: "Approved",
    date: "28 Aug, 10:42",
  },
  {
    id: "NX-84028",
    customer: "Northstar",
    value: 490,
    method: "Mastercard •••• 8812",
    status: "Approved",
    date: "28 Aug, 09:18",
  },
  {
    id: "NX-84027",
    customer: "Atlas Health",
    value: 490,
    method: "Visa •••• 1094",
    status: "Failed",
    date: "27 Aug, 18:03",
  },
  {
    id: "NX-84026",
    customer: "Lumina Studio",
    value: 190,
    method: "Pix",
    status: "Pending",
    date: "27 Aug, 15:44",
  },
  {
    id: "NX-84025",
    customer: "Vero Finance",
    value: 1290,
    method: "Amex •••• 2018",
    status: "Refunded",
    date: "26 Aug, 12:11",
  },
];

export const members = [
  {
    name: "Isabela Rocha",
    email: "isabela@nexus.app",
    role: "Owner",
    title: "Founder & CEO",
    initials: "IR",
    status: "Active",
  },
  {
    name: "Lucas Azevedo",
    email: "lucas@nexus.app",
    role: "Admin",
    title: "Head of Product",
    initials: "LA",
    status: "Active",
  },
  {
    name: "Bia Santos",
    email: "bia@nexus.app",
    role: "Manager",
    title: "Customer Success",
    initials: "BS",
    status: "Active",
  },
  {
    name: "Renan Melo",
    email: "renan@nexus.app",
    role: "Member",
    title: "Product Designer",
    initials: "RM",
    status: "Away",
  },
];

